version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

    ports:
      - "3306:3306"
    volumes:

      - mysql_data:/var/lib/mysql

      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  mysql_data:
